### ISSUE TITLE
Trello like board

### ISSUE THREAD

**Issue by tiboCorb** [jenaye/Tipnturn-front#40]
Possiblity to creat issues and assignee some one to it , posibility to move issue between several state (todo , work  in progress, done) with drag and drop

**Comment by tiboCorb** [comment]
we have change our api model with folowing :
{Tag, 
Title,
Users,
Deadline,
Commentaire
State}

**Comment by jenaye** [comment]
Ok i'll update database schema today,
btw, we should close only after done the issue @tiboCorb

**Comment by jenaye** [comment]
@tiboCorb , its done, u can do the front part :)

**Comment by jenaye** [comment]
WIP https://github.com/jenaye/Tipnturn-front/pull/51

**Comment by jenaye** [comment]
done in #51  by @tiboCorb thx a lot for this one
![unknown 1](https://user-images.githubusercontent.com/15458329/42568455-78aaec00-850d-11e8-9d2b-b7b6ec7cb39e.png)
