### ISSUE TITLE
Event and google maps

### ISSUE THREAD

**Issue by jenaye** [jenaye/Tipnturn-front#9]
- [ ] Add possibility to create event
- [ ] Add google maps

API_KEY already exist in config.js

**Comment by jenaye** [comment]
coucou

**Comment by tiboCorb** [comment]
je fait des tests

**Comment by tiboCorb** [comment]
coucou

**Comment by tiboCorb** [comment]
coucou

**Comment by tiboCorb** [comment]
coucou

**Comment by tiboCorb** [comment]
coucou

**Comment by tiboCorb** [comment]
coucou

**Comment by tiboCorb** [comment]
salut

**Comment by tiboCorb** [comment]
salut

**Comment by tiboCorb** [comment]
test ultime

**Comment by tiboCorb** [comment]
les test

**Comment by tiboCorb** [comment]
test 16.10

**Comment by tiboCorb** [comment]
hello

**Comment by tiboCorb** [comment]
joe

**Comment by tiboCorb** [comment]
test message

**Comment by tiboCorb** [comment]
hello

**Comment by tiboCorb** [comment]
adf"ézr

**Comment by tiboCorb** [comment]
dsl mais sa marche super chez toi

**Comment by jenaye** [comment]
![image](https://user-images.githubusercontent.com/15458329/37492947-8f04bfec-28a3-11e8-8637-9c234a79b238.png)

Atm Event available on api we only need to create it here
@tiboCorb

**Comment by tiboCorb** [comment]
we need to add google maps for event location with possibility to copy and share by button
in API we already have the route /events who can give all informations
